gBirchSpeech_Welcome:: @ 81C6D78
	.string "Hello there!\p"
	.string "Welcome to the Land of Zarahemla!\p"
	.string "My name is MORONI.\p"
	.string "I’m the captain over the armies\n"
	.string "of my people, the NEPHITES.\p$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "This is what we call a “POKéMON.”$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "We are amidst troubling times.\n"
	.string "A traitor from among us,\l"
	.string "AMALICKIAH, has sought to obtain\l"
	.string "power in every abominable way.\p"
	.string "He has flattered the hearts of many\n"
	.string "to follow after him.\p"
	.string "He has gone to our bretheren,\n"
	.string "the LAMANITES, to stir them to go\l"
	.string "to war against us.\p"
	.string "While I have dispatched many men\n"
	.string "with swords, cimeters, and other\l"
	.string "weapons, you will not be using\l"
	.string "such a thing.\p"
	.string "Instead, you will be sent as a\n"
	.string "special force to weaken the armies\l"
	.string "of the LAMANITES with POKéMON.\p$"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "With all that being said...$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "All right.\n"
	.string "What’s your name?$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "So it’s {PLAYER}{KUN}?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
    .string "{PLAYER}{KUN}.\p"
	.string "Surely, you will be a great\n"
	.string "strength to my army.\p$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "Move out, there’s no time to waste!\p$"
