InsideOfTruck_MapWarps::
	warp_def 20, 8, 0, 2, MAP_INSIDE_OF_TRUCK
	warp_def 21, 8, 0, 3, MAP_INSIDE_OF_TRUCK
	warp_def 20, 1, 0, 0, MAP_INSIDE_OF_TRUCK
	warp_def 21, 1, 3, 1, MAP_INSIDE_OF_TRUCK
	warp_def 27, 22, 3, 6, MAP_INSIDE_OF_TRUCK
	warp_def 28, 22, 3, 7, MAP_INSIDE_OF_TRUCK
	warp_def 8, 22, 3, 0, MAP_INSIDE_OF_TRUCK
	warp_def 42, 13, 3, 0, MAP_INSIDE_OF_TRUCK
	warp_def 42, 22, 3, 0, MAP_INSIDE_OF_TRUCK

InsideOfTruck_MapEvents::
	map_events 0x0, InsideOfTruck_MapWarps, 0x0, 0x0
